version: '3'
services:
  tzdz:
    image: imooc/tzdz:latest
    container_name: mailserver
    networks:
      - custom_net
    ports:
      - "80:8080"
    restart: always
    entrypoint: "java -jar -Xms256m -Xmx512m /app.jar"

  nginx_tzdz:
    networks:
      - custom_net
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /root:/root
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  custom_net:
    external:
      name: app_net

