version: '3'
services:
  tzdz:
    image: imooc/tzdz:latest
    container_name: tzdz
    networks:
      - custom_net
    ports:
      - "8081:8080"
    restart: always
    entrypoint: "java -jar -Xms256m -Xmx512m /app.jar"


networks:
  custom_net:
    external:
      name: app_net

